<?php

/**
 * @file
 * Empty on purpose.
 *
 * This file exists as a workaround for a problem that was inherited by the 7.x
 * version of this module: all module files are named views_filters_selective.xyz, but they live
 * inside a views_selective_filters folder (but no matching views_selective_filters.info and
 * views_selective_filters.module files).
 * See https://github.com/backdrop-contrib/views_selective_filters/issues/9
 */
